### ISSUE TITLE
improving cutnumeric

### ISSUE THREAD

**Issue by soodoku** [masspastore/overlapping#7]
Dear @masspastore,

this doesn't technically impact your submission to JOSS. This is just me suggesting ways to improve code, etc. 

```
cutnumeric <-
function(x, n = 1000 ) {
  ## x = a numeric vector
  if(!is.numeric(x)) stop("x must be numeric")
  
  xclass <- cut(x, seq( min(x), max(x), length = n ), include.lowest = TRUE )
  xnumeric <- NULL
  for (l in xclass) {
    h <- strsplit(l, "," )[[1]]
    h <- gsub( "\\[", "", gsub("\\]", "", gsub("\\(", "", h ) ) )
    xnumeric <- c(xnumeric, mean(as.numeric(h)) )
  } 
  return(xnumeric)
}
```

Here are my recommendations for the function:

a. document it --- parameters + outputs always need to be documented + line about key functionality + ideally an example. see roxygen for an easy way to do this.
b. think about allowing users to pass a value of n. It isn't clear why n= 1000 is optimal everywhere. Depends on how much data, no?
c. explicit return is not required in R. just drop return()
d. for loop is not good for just adding means of the buckets. vectorization is the way to go.

**Comment by soodoku** [comment]
I may submit a PR around this just to help out.

**Comment by masspastore** [comment]
Hi @soodoku, thank you for your suggestions.

I substituted the for loop with the function lapply(), and added some comments (in roxygen style).

The parameter n represents the number of bins for estimating density and do not depends on sample size. In my experience 1000 is a good number and should be changed only in particular cases. I did not report a detailed description about it because cutnumeric is an internal function and is not particularly useful for other purposes.

**Comment by soodoku** [comment]
awesome @masspastore!

the function `overlap` takes nbins as an argument that the user can pass. you would want to pass that argument to `cutnumeric`. makes sense?

**Comment by masspastore** [comment]
Yes @soodoku, 

in my opinion is better to leave this possibility for particluar cases.

For example, if your x variable has a large dominion, such as reaction times expresses in milliseconds, n = 1000 could be a non optimal choice. 

Note that I changed even the call to cutnumeric in the overlap function (line 24).

**Comment by soodoku** [comment]
great.
